version: "3"
services:
    message:
        image: rabbitmq:management
        ports:
            - 5672:5672
            - 15672:15672
            - 25672:25672
    test_web:
        image: nginx
        expose:
            - 80
        ports:
            - 80:80
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - flask
    database:
        image: mysql:5.7
        container_name: database
        ports:
            - "3306:3306"
        environment: 
            MYSQL_DATABASE: test_db
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_USER: web
            MYSQL_PASSWORD: 1234
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./database/data:/var/lib/mysql
    flask:
        build:
            context: ./python
        ports:
            - 5000:5000
        depends_on:
            - message
        restart:
            always
    #review:
    #    build: ./spring
    #    expose:
    #        - 8080
    #    ports:
    #        - 8080:8080