version: "3"
services: 
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: web
      MYSQL_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - C:\Users\Home\docker\database\data:/var/lib/mysql